---
Applikation: "myfactory"
Namespace: "beltsparadise"

#only one release per namespace can manage the builressources, so this is only allowed to be `true` once per namespace
createBuildResources: true
Version: 1.1.104
SHA256: 8e13353ab23d57989db7b06594411d30885de1a923f3a989d12749c1abc01583

#currently only nfs storage backend with a fixed ip adress and storagepath is supported
StorageServerIP: 10.100.1.2

env:
      - UPDATE_MODS_ON_START=true
#      - USERNAME=FactorioUsername
#      - TOKEN=FactorioToken