---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Applikation }}
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.Applikation }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.Applikation }}
    spec:
      {{ if (default .Values.ocp "false") }}
      securityContext:
        runAsUser: 845
        runAsGroup: 845
        fsGroup: 0
      {{ end }}
      containers:
        - name: factorio-dedicated-server
          {{ if and (.Values.createBuildResources) (.Values.ocp) }}
          image: "image-registry.openshift-image-registry.svc:5000/{{ .Values.Namespace }}/factorio-ocp:latest"
          {{ else }}
          image: "ghcr.io/cardes/factorio-docker-ocp:{{ .Values.Version}}"
          {{ end }}
          ports:
            - name: gameserver
              containerPort: 34197
              protocol: UDP
          envFrom:
            - configMapRef:
                name: {{ .Values.Applikation }}-env
          volumeMounts:
            - name: game-volume
              mountPath: /factorio
      volumes:
        - name: game-volume
          persistentVolumeClaim:
            claimName: {{ .Values.Applikation }}-data
