---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.namespace }}-{{ .Values.application }}-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4.1
  claimRef:
    name: {{ .Values.application }}-data
    kind: persistentVolumeClaim
    namespace: {{ .Values.namespace }}
  storageClassName: manual
  nfs:
    path: /kubes/manual-{{ .Values.namespace }}-{{ .Values.application }}-data
    server: {{ .Values.storageServerIP }}