---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.application }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.application }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancerIP }}
spec:
  ipFamilies:
    - IPv4
  externalTrafficPolicy: Local
  ports:
    - name: gameserver
      port: 34197
      protocol: UDP
      targetPort: 34197
  internalTrafficPolicy: Cluster
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{ .Values.application }}
