---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.Applikation }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.Applikation }}
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: gameserver
      port: 8211
      protocol: UDP
      targetPort: 8211
  internalTrafficPolicy: Cluster
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{ .Values.Applikation }}
